/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.59
 * Generated at: 2022-05-10 13:00:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.QuanLy;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class nhanvien_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/C:/WebXeKhach/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/CNPM/WEB-INF/lib/jstl-impl.jar!/META-INF/c.tld", Long.valueOf(1343794618000L));
    _jspx_dependants.put("/WEB-INF/views/QuanLy/head.jsp", Long.valueOf(1652179661718L));
    _jspx_dependants.put("/WEB-INF/views/QuanLy/slidebar.jsp", Long.valueOf(1652179759282L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-impl.jar", Long.valueOf(1651728372000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write(" <!-- ======= Header ======= -->\r\n");
      out.write("    <header id=\"header\" class=\"header fixed-top d-flex align-items-center\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"d-flex align-items-center justify-content-between\">\r\n");
      out.write("            <a href=\"index.html\" class=\"logo d-flex align-items-center\">\r\n");
      out.write("                <img src=\"../assets/img/logo.png\" alt=\"\">\r\n");
      out.write("                <span class=\"d-none d-lg-block\">NiceAdmin</span>\r\n");
      out.write("            </a>\r\n");
      out.write("            <i class=\"bi bi-list toggle-sidebar-btn\"></i>\r\n");
      out.write("        </div><!-- End Logo -->\r\n");
      out.write("\r\n");
      out.write("        <nav class=\"header-nav ms-auto\">\r\n");
      out.write("            <ul class=\"d-flex align-items-center\">\r\n");
      out.write("\r\n");
      out.write("                <li class=\"nav-item d-block d-lg-none\">\r\n");
      out.write("                    <a class=\"nav-link nav-icon search-bar-toggle \" href=\"#\">\r\n");
      out.write("                        <i class=\"bi bi-search\"></i>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li><!-- End Search Icon-->\r\n");
      out.write("\r\n");
      out.write("                <li class=\"nav-item dropdown pe-3 me-2\">\r\n");
      out.write("\r\n");
      out.write("                    <a class=\"nav-link nav-profile d-flex align-items-center pe-0\" href=\"#\" data-bs-toggle=\"dropdown\">\r\n");
      out.write("                        <img src=\"../assets/img/profile-img.jpg\" alt=\"Profile\" class=\"rounded-circle\">\r\n");
      out.write("                        <span class=\"d-none d-md-block dropdown-toggle ps-2\">K. Anderson</span>\r\n");
      out.write("                    </a><!-- End Profile Iamge Icon -->\r\n");
      out.write("\r\n");
      out.write("                    <ul class=\"dropdown-menu dropdown-menu-end dropdown-menu-arrow profile v-drop-profile\">\r\n");
      out.write("                        <li class=\"dropdown-header\">\r\n");
      out.write("                            <h6>Kevin Anderson</h6>\r\n");
      out.write("                            <span>Web Designer</span>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <hr class=\"dropdown-divider\">\r\n");
      out.write("                        </li>\r\n");
      out.write("\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a class=\"dropdown-item d-flex align-items-center\" href=\"QL_TrangCaNhan.html\">\r\n");
      out.write("                                <i class=\"bi bi-person\"></i>\r\n");
      out.write("                                <span>Tài khoản của tôi</span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <hr class=\"dropdown-divider\">\r\n");
      out.write("                        </li>\r\n");
      out.write("\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a class=\"dropdown-item d-flex align-items-center\" href=\"QL_Dangnhap.html\">\r\n");
      out.write("                                <i class=\"bi bi-box-arrow-right\"></i>\r\n");
      out.write("                                <span>Đăng xuất</span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("\r\n");
      out.write("                    </ul><!-- End Profile Dropdown Items -->\r\n");
      out.write("                </li><!-- End Profile Nav -->\r\n");
      out.write("\r\n");
      out.write("            </ul>\r\n");
      out.write("        </nav><!-- End Icons Navigation -->\r\n");
      out.write("\r\n");
      out.write("    </header><!-- End Header -->\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<meta charset=\"utf-8\" />\r\n");
      out.write("  <meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\" />\r\n");
      out.write("\r\n");
      out.write("  <title>Components / Accordion - NiceAdmin Bootstrap Template</title>\r\n");
      out.write("  <meta content=\"\" name=\"description\" />\r\n");
      out.write("  <meta content=\"\" name=\"keywords\" />\r\n");
      out.write("\r\n");
      out.write("  <!-- Favicons -->\r\n");
      out.write("  <link href=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\" rel=\"icon\" />\r\n");
      out.write("  <link href=\"");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("\" rel=\"apple-touch-icon\" />\r\n");
      out.write("\r\n");
      out.write("  <!-- Google Fonts -->\r\n");
      out.write("  <link href=\"https://fonts.gstatic.com\" rel=\"preconnect\" />\r\n");
      out.write("  <link\r\n");
      out.write("    href=\"https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i\"\r\n");
      out.write("    rel=\"stylesheet\" />\r\n");
      out.write("\r\n");
      out.write("  <!-- Vendor CSS Files -->\r\n");
      out.write(" ");
      out.write("\r\n");
      out.write("  <link href=\"");
      if (_jspx_meth_c_005furl_005f2(_jspx_page_context))
        return;
      out.write("\" rel=\"stylesheet\" />\r\n");
      out.write("  <link href=\"");
      if (_jspx_meth_c_005furl_005f3(_jspx_page_context))
        return;
      out.write("\" rel=\"stylesheet\" />\r\n");
      out.write("  <link href=\"");
      if (_jspx_meth_c_005furl_005f4(_jspx_page_context))
        return;
      out.write("\" rel=\"stylesheet\" />\r\n");
      out.write("  <link href=\"");
      if (_jspx_meth_c_005furl_005f5(_jspx_page_context))
        return;
      out.write("\" rel=\"stylesheet\" />\r\n");
      out.write("  <link href=\"");
      if (_jspx_meth_c_005furl_005f6(_jspx_page_context))
        return;
      out.write("\" rel=\"stylesheet\" />\r\n");
      out.write("  <link href=\"");
      if (_jspx_meth_c_005furl_005f7(_jspx_page_context))
        return;
      out.write("\" rel=\"stylesheet\" />\r\n");
      out.write("  <link href=\"");
      if (_jspx_meth_c_005furl_005f8(_jspx_page_context))
        return;
      out.write("\" rel=\"stylesheet\" />\r\n");
      out.write("\r\n");
      out.write("  <!-- Template Main CSS File -->\r\n");
      out.write("  <link href=\"");
      if (_jspx_meth_c_005furl_005f9(_jspx_page_context))
        return;
      out.write("\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("  <link href=\"");
      if (_jspx_meth_c_005furl_005f10(_jspx_page_context))
        return;
      out.write("\" rel=\"stylesheet\" />\r\n");
      out.write("  <!-- =======================================================\r\n");
      out.write("  * Template Name: NiceAdmin - v2.2.2\r\n");
      out.write("  * Template URL: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/\r\n");
      out.write("  * Author: BootstrapMade.com\r\n");
      out.write("  * License: https://bootstrapmade.com/license/\r\n");
      out.write("  ======================================================== -->");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<aside id=\"sidebar\" class=\"sidebar\">\r\n");
      out.write("    <ul class=\"sidebar-nav\" id=\"sidebar-nav\">\r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("        <a class=\"nav-link collapsed\" href=\"QL_TrangChu.html\">\r\n");
      out.write("          <i class=\"ri-home-4-line\r\n");
      out.write("          \"></i>\r\n");
      out.write("          <span>Trang Chủ</span>\r\n");
      out.write("        </a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <hr style=\"margin:0\">\r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("        <a class=\"nav-link collapsed\" href=\"QL_ChuyenXe.html\">\r\n");
      out.write("          <i class=\"ri-bus-line\"></i>\r\n");
      out.write("          <span>Chuyến Xe</span>\r\n");
      out.write("        </a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <!-- End Profile Page Nav -->\r\n");
      out.write("\r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("        <a class=\"nav-link collapsed\" href=\"QL_TuyenXe.html\">\r\n");
      out.write("          <i class=\"ri-arrow-left-right-line\"></i>\r\n");
      out.write("          <span>Tuyến Xe</span>\r\n");
      out.write("        </a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <!-- End F.A.Q Page Nav -->\r\n");
      out.write("\r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("        <a class=\"nav-link collapsed\" href=\"QL_NhanVien.html\">\r\n");
      out.write("          <i class=\"ri-contacts-line\"></i>\r\n");
      out.write("          <span>Nhân Viên</span>\r\n");
      out.write("        </a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <!-- End Contact Page Nav -->\r\n");
      out.write("\r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("        <a class=\"nav-link collapsed\" href=\"QL_KhachHang.html\">\r\n");
      out.write("          <i class=\"bi bi-people\"></i>\r\n");
      out.write("          <span>Khách Hàng</span>\r\n");
      out.write("        </a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <!-- End Register Page Nav -->\r\n");
      out.write("\r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("        <a class=\"nav-link collapsed\" href=\"QL_DiaDiem.html\">\r\n");
      out.write("          <i class=\"bi bi-pin-map-fill\"></i>\r\n");
      out.write("          <span>Địa Điểm</span>\r\n");
      out.write("        </a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <!-- End Login Page Nav -->\r\n");
      out.write("\r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("        <a class=\"nav-link collapsed\" href=\"QL_LoaiXe.html\">\r\n");
      out.write("          <i class=\"ri-align-justify\"></i>\r\n");
      out.write("          <span>Loại Xe</span>\r\n");
      out.write("        </a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <!-- End Error 404 Page Nav -->\r\n");
      out.write("\r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("        <a class=\"nav-link collapsed\" href=\"QL_BangGia.html\">\r\n");
      out.write("          <i class=\"bi bi-currency-dollar\"></i>\r\n");
      out.write("          <span>Bảng Giá</span>\r\n");
      out.write("        </a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <!-- End Blank Page Nav -->\r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("        <a class=\"nav-link\" href=\"QL_PhieuDat.html\">\r\n");
      out.write("          <i class=\"bi bi-clipboard\"></i>\r\n");
      out.write("          <span>Phiếu Đặt</span>\r\n");
      out.write("        </a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <!-- End Blank Page Nav -->\r\n");
      out.write("    </ul>\r\n");
      out.write("  </aside>\r\n");
      out.write("  <!-- End Sidebar-->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <main id=\"main\" class=\"main\">\r\n");
      out.write("        <div class=\"pagetitle\">\r\n");
      out.write("            <h1>Nhân Viên</h1>\r\n");
      out.write("        </div><!-- End Page Title -->\r\n");
      out.write("        <button type=\"button\" class=\"btn add-new btn-outline-danger shadow-none\" data-bs-toggle=\"modal\"\r\n");
      out.write("            data-bs-target=\"#verticalycentered\">\r\n");
      out.write("            Thêm mới <i class=\"bi bi-person-plus\"></i>\r\n");
      out.write("        </button>\r\n");
      out.write("        <section class=\"section\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-lg-12\">\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("\r\n");
      out.write("                        <!-- Table with stripped rows -->\r\n");
      out.write("                        <table class=\"table datatable table-striped table-bordered\">\r\n");
      out.write("                            <thead>\r\n");
      out.write("                                <tr class=\"v-table-tr-color\">\r\n");
      out.write("                                    <th scope=\"col\">Mã nhân viên</th>\r\n");
      out.write("                                    <th scope=\"col\">Họ</th>\r\n");
      out.write("                                    <th scope=\"col\">Tên</th>\r\n");
      out.write("                                    <th scope=\"col\">Username</th>\r\n");
      out.write("                                    <th scope=\"col\">Trạng Thái</th>\r\n");
      out.write("                                    <th scope=\"col\">Option</th>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                            </thead>\r\n");
      out.write("                            <tbody>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <th scope=\"row\">NV001</th>\r\n");
      out.write("                                    <td>Nguyễn</td>\r\n");
      out.write("                                    <td>Thị Khánh Vi</td>\r\n");
      out.write("                                    <td>nv001</td>\r\n");
      out.write("                                    <td>\r\n");
      out.write("                                        <span class=\"badge rounded-pill bg-success v-bg-tt\">Hoạt động</span>\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                    <td>\r\n");
      out.write("\r\n");
      out.write("                                        <span>\r\n");
      out.write("                                            <i class=\"bi bi-info-circle-fill v-icon-modal\" data-bs-toggle=\"modal\"\r\n");
      out.write("                                                data-bs-target=\"#ProfileViewModal\"></i>\r\n");
      out.write("                                            <i class=\"bi bi-pencil-square v-icon-modal\" data-bs-toggle=\"modal\"\r\n");
      out.write("                                                data-bs-target=\"#ProfileEditModal\"></i>\r\n");
      out.write("                                        </span>\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <th scope=\"row\">2</th>\r\n");
      out.write("                                    <td>Bridie Kessler</td>\r\n");
      out.write("                                    <td>Developer</td>\r\n");
      out.write("                                    <td>35</td>\r\n");
      out.write("                                    <td>\r\n");
      out.write("                                        <span class=\"badge rounded-pill bg-success v-bg-tt\">Hoạt động</span>\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                    <td>\r\n");
      out.write("\r\n");
      out.write("                                        <span>\r\n");
      out.write("                                            <i class=\"bi bi-info-circle-fill v-icon-modal\" data-bs-toggle=\"modal\"\r\n");
      out.write("                                                data-bs-target=\"#ProfileViewModal\"></i>\r\n");
      out.write("                                            <i class=\"bi bi-pencil-square v-icon-modal\" data-bs-toggle=\"modal\"\r\n");
      out.write("                                                data-bs-target=\"#ProfileEditModal\"></i>\r\n");
      out.write("                                        </span>\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <th scope=\" row\">3</th>\r\n");
      out.write("                                    <td>Ashleigh Langosh</td>\r\n");
      out.write("                                    <td>Finance</td>\r\n");
      out.write("                                    <td>45</td>\r\n");
      out.write("                                    <td>\r\n");
      out.write("                                        <span class=\"badge rounded-pill bg-success v-bg-tt\">Hoạt động</span>\r\n");
      out.write("                                    </td>\r\n");
      out.write("\r\n");
      out.write("                                    <td>\r\n");
      out.write("                                        <span>\r\n");
      out.write("                                            <i class=\"bi bi-info-circle-fill v-icon-modal\" data-bs-toggle=\"modal\"\r\n");
      out.write("                                                data-bs-target=\"#ProfileViewModal\"></i>\r\n");
      out.write("                                            <i class=\"bi bi-pencil-square v-icon-modal\" data-bs-toggle=\"modal\"\r\n");
      out.write("                                                data-bs-target=\"#ProfileEditModal\"></i>\r\n");
      out.write("                                        </span>\r\n");
      out.write("\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <th scope=\"row\">4</th>\r\n");
      out.write("                                    <td>Angus Grady</td>\r\n");
      out.write("                                    <td>HR</td>\r\n");
      out.write("                                    <td>34</td>\r\n");
      out.write("                                    <td>\r\n");
      out.write("                                        <span type=\"button\" class=\"badge rounded-pill bg-danger v-bg-tt\">Khóa</span>\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                    <td>\r\n");
      out.write("                                        <span>\r\n");
      out.write("                                            <i class=\"bi bi-info-circle-fill v-icon-modal\" data-bs-toggle=\"modal\"\r\n");
      out.write("                                                data-bs-target=\"#ProfileViewModal\"></i>\r\n");
      out.write("                                            <i class=\"bi bi-pencil-square v-icon-modal\" data-bs-toggle=\"modal\"\r\n");
      out.write("                                                data-bs-target=\"#ProfileEditModal\"></i>\r\n");
      out.write("                                        </span>\r\n");
      out.write("\r\n");
      out.write("                                    </td>\r\n");
      out.write("\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <th scope=\"row\">5</th>\r\n");
      out.write("                                    <td>Raheem Lehner</td>\r\n");
      out.write("                                    <td>Dynamic Division Officer</td>\r\n");
      out.write("                                    <td>47</td>\r\n");
      out.write("                                    <td>\r\n");
      out.write("                                        <span type=\"button\" class=\"badge rounded-pill bg-danger v-bg-tt\">Khóa</span>\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                    <td>\r\n");
      out.write("                                        <span>\r\n");
      out.write("                                            <i class=\"bi bi-info-circle-fill v-icon-modal\" data-bs-toggle=\"modal\"\r\n");
      out.write("                                                data-bs-target=\"#ProfileViewModal\"></i>\r\n");
      out.write("                                            <i class=\"bi bi-pencil-square v-icon-modal\" data-bs-toggle=\"modal\"\r\n");
      out.write("                                                data-bs-target=\"#ProfileEditModal\"></i>\r\n");
      out.write("                                        </span>\r\n");
      out.write("\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                            </tbody>\r\n");
      out.write("                        </table>\r\n");
      out.write("                        <!-- End Table with stripped rows -->\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("\r\n");
      out.write("    </main><!-- End #main -->\r\n");
      out.write("    <!-- ProfileViewModal -->\r\n");
      out.write("    <div class=\"modal fade\" id=\"ProfileViewModal\" tabindex=\"-1\">\r\n");
      out.write("        <div class=\"modal-dialog v-modal-container\">\r\n");
      out.write("            <div class=\"modal-content border-0\">\r\n");
      out.write("                <div class=\"modal-header v-modal-header\">\r\n");
      out.write("                    <h5 class=\"modal-title v-modal-title\">Thông tin</h5>\r\n");
      out.write("                    <button type=\"button\" class=\"btn shadow-none\" data-bs-dismiss=\"modal\" aria-label=\"Close\"\r\n");
      out.write("                        style=\"font-weight:700\"><i class=\"bi bi-x v-icon-close\"></i></button>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"modal-body\">\r\n");
      out.write("                    <!-- profile -->\r\n");
      out.write("                    <main id=\"modal-main\" class=\"main\">\r\n");
      out.write("\r\n");
      out.write("                        <section class=\"section profile\">\r\n");
      out.write("                            <div class=\"row \">\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"col-xl-12\">\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"card mb-0\">\r\n");
      out.write("                                        <div class=\"card-body pt-3\">\r\n");
      out.write("                                            <div class=\"tab-content pt-2\">\r\n");
      out.write("\r\n");
      out.write("                                                <div class=\"tab-pane fade show active profile-overview\"\r\n");
      out.write("                                                    id=\"profile-overview\">\r\n");
      out.write("\r\n");
      out.write("                                                    <div class=\"row\">\r\n");
      out.write("                                                        <div class=\"col-lg-3 col-md-4 label v-label \">Mã nhân viên</div>\r\n");
      out.write("                                                        <div class=\"col-lg-9 col-md-8\">NV01</div>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                                    <div class=\"row\">\r\n");
      out.write("                                                        <div class=\"col-lg-3 col-md-4 label v-label\">Họ</div>\r\n");
      out.write("                                                        <div class=\"col-lg-9 col-md-8\">Lueilwitz\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                                    <div class=\"row\">\r\n");
      out.write("                                                        <div class=\"col-lg-3 col-md-4 label v-label\">Tên</div>\r\n");
      out.write("                                                        <div class=\"col-lg-9 col-md-8\">Web Designer</div>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                                    <div class=\"row\">\r\n");
      out.write("                                                        <div class=\"col-lg-3 col-md-4 label v-label\">Vai trò</div>\r\n");
      out.write("                                                        <div class=\"col-lg-9 col-md-8\">Web Designer</div>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                                    <div class=\"row\">\r\n");
      out.write("                                                        <div class=\"col-lg-3 col-md-4 label v-label\">Email</div>\r\n");
      out.write("                                                        <div class=\"col-lg-9 col-md-8\">Web Designer</div>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                                    <div class=\"row\">\r\n");
      out.write("                                                        <div class=\"col-lg-3 col-md-4 label v-label\">Phái</div>\r\n");
      out.write("                                                        <div class=\"col-lg-9 col-md-8\">k.anderson@example.com</div>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                    <div class=\"row\">\r\n");
      out.write("                                                        <div class=\"col-lg-3 col-md-4 label v-label\">Trạng thái</div>\r\n");
      out.write("                                                        <div class=\"col-lg-9 col-md-8\">k.anderson@example.com</div>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                    <div class=\"row\">\r\n");
      out.write("                                                        <div class=\"col-lg-3 col-md-4 label v-label\">CMND/CCCD</div>\r\n");
      out.write("                                                        <div class=\"col-lg-9 col-md-8\">USA</div>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                                    <div class=\"row\">\r\n");
      out.write("                                                        <div class=\"col-lg-3 col-md-4 label v-label\">SĐT</div>\r\n");
      out.write("                                                        <div class=\"col-lg-9 col-md-8\">A108 Adam Street, New York, NY\r\n");
      out.write("                                                            535022</div>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                                    <div class=\"row\">\r\n");
      out.write("                                                        <div class=\"col-lg-3 col-md-4 label v-label\">Ngày sinh</div>\r\n");
      out.write("                                                        <div class=\"col-lg-9 col-md-8\">(436) 486-3538 x29071</div>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div><!-- End Bordered Tabs -->\r\n");
      out.write("\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </section>\r\n");
      out.write("\r\n");
      out.write("                    </main>\r\n");
      out.write("\r\n");
      out.write("                    <!-- end profile -->\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- End ProfileViewModal-->\r\n");
      out.write("    <!-- ProfileEditModal -->\r\n");
      out.write("    <div class=\"modal fade\" id=\"ProfileEditModal\" tabindex=\"-1\">\r\n");
      out.write("        <div class=\"modal-dialog v-modal-container\">\r\n");
      out.write("            <div class=\"modal-content border-0\">\r\n");
      out.write("                <div class=\"modal-header v-modal-header\">\r\n");
      out.write("                    <h5 class=\"modal-title v-modal-title\">Chỉnh sửa</h5>\r\n");
      out.write("                    <button type=\"button\" class=\"btn shadow-none\" data-bs-dismiss=\"modal\" aria-label=\"Close\"\r\n");
      out.write("                        style=\"font-weight:700\"><i class=\"bi bi-x v-icon-close\"></i></button>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"modal-body row\">\r\n");
      out.write("                    <!-- profile -->\r\n");
      out.write("                    <!-- Profile Edit Form -->\r\n");
      out.write("                    <div class=\"col-12 v-edit-form\">\r\n");
      out.write("                        <form>\r\n");
      out.write("                            <div class=\"row mb-3\">\r\n");
      out.write("                                <label for=\"fullName\" class=\"col-md-4 col-lg-3 col-form-label v-label\">Mã nhân\r\n");
      out.write("                                    viên</label>\r\n");
      out.write("                                <div class=\"col-md-8 col-lg-9\">\r\n");
      out.write("                                    <input name=\"fullName\" type=\"text\" class=\"form-control v-form-control\" id=\"fullName\"\r\n");
      out.write("                                        value=\"Kevin Anderson\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"row mb-3\">\r\n");
      out.write("                                <label for=\"company\" class=\"col-md-3 col-form-label v-label\">Họ</label>\r\n");
      out.write("                                <div class=\"col-md-3\">\r\n");
      out.write("                                    <input name=\"company\" type=\"text\" class=\"form-control v-form-control\" id=\"company\"\r\n");
      out.write("                                        value=\"Lueilwitz, Wisoky and Leuschke\">\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                                <label for=\"Job\" class=\"col-md-1 col-form-label v-label\">Tên</label>\r\n");
      out.write("                                <div class=\"col-md-5\">\r\n");
      out.write("                                    <input name=\"job\" type=\"text\" class=\"form-control  v-form-control\" id=\"Job\"\r\n");
      out.write("                                        value=\"Web Designer\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"row mb-3\">\r\n");
      out.write("                                <label for=\"Twitter\" class=\"col-md-4 col-lg-3 col-form-label v-label\">Username</label>\r\n");
      out.write("                                <div class=\"col-md-8 col-lg-9\">\r\n");
      out.write("                                    <input name=\"twitter\" type=\"text\" class=\"form-control v-form-control\" id=\"Twitter\"\r\n");
      out.write("                                        value=\"https://twitter.com/#\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"row mb-3\">\r\n");
      out.write("                                <label for=\"Twitter\" class=\"col-md-4 col-lg-3 col-form-label v-label\">Email</label>\r\n");
      out.write("                                <div class=\"col-md-8 col-lg-9\">\r\n");
      out.write("                                    <input type=\"email\" class=\"form-control v-form-control\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"row mb-3\">\r\n");
      out.write("                                <label for=\"Twitter\" class=\"col-md-4 col-lg-3 col-form-label v-label\">Mật Khẩu</label>\r\n");
      out.write("                                <div class=\"col-md-8 col-lg-9\">\r\n");
      out.write("                                    <input type=\"password\" class=\"form-control v-form-control\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"row mb-3\">\r\n");
      out.write("                                <label for=\"Twitter\" class=\"col-md-4 col-lg-3 col-form-label v-label\">Nhập lại mật\r\n");
      out.write("                                    Khẩu</label>\r\n");
      out.write("                                <div class=\"col-md-8 col-lg-9\">\r\n");
      out.write("                                    <input type=\"password\" class=\"form-control v-form-control\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"row mb-3\">\r\n");
      out.write("                                <label for=\"Twitter\" class=\"col-md-4 col-lg-3 col-form-label v-label\">Vai trò</label>\r\n");
      out.write("                                <div class=\"col-md-8 col-lg-9\">\r\n");
      out.write("                                    <select class=\"form-select v-form-control\" aria-label=\" select example\">\r\n");
      out.write("                                        <option selected value=\"1\">One</option>\r\n");
      out.write("                                        <option value=\"2\">Two</option>\r\n");
      out.write("                                        <option value=\"3\">Three</option>\r\n");
      out.write("                                    </select>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"row mb-3\">\r\n");
      out.write("                                <label for=\"Country\" class=\"col-md-4 col-lg-3 col-form-label v-label\">CMND/CCCD</label>\r\n");
      out.write("                                <div class=\"col-md-8 col-lg-9\">\r\n");
      out.write("                                    <input name=\"country\" type=\"text\" class=\"form-control v-form-control\" id=\"Country\"\r\n");
      out.write("                                        value=\"USA\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"row mb-3\">\r\n");
      out.write("                                <label for=\"Address\" class=\"col-md-4 col-lg-3 col-form-label v-label\">SĐT</label>\r\n");
      out.write("                                <div class=\"col-md-8 col-lg-9\">\r\n");
      out.write("                                    <input name=\"address\" type=\"text\" class=\"form-control v-form-control\" id=\"Address\"\r\n");
      out.write("                                        value=\"A108 Adam Street, New York, NY 535022\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"row mb-3\">\r\n");
      out.write("                                <label for=\"Phone\" class=\"col-md-4 col-lg-3 col-form-label v-label\">Ngày sinh</label>\r\n");
      out.write("                                <div class=\"col-md-8 col-lg-9\">\r\n");
      out.write("                                    <input name=\"phone\" type=\"text\" class=\"form-control v-form-control\" id=\"Phone\"\r\n");
      out.write("                                        value=\"(436) 486-3538 x29071\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"row mb-3\">\r\n");
      out.write("                                <label for=\"Email\" class=\"col-md-4 col-lg-3 col-form-label v-label\">Phái</label>\r\n");
      out.write("                                <div class=\"col-md-8\">\r\n");
      out.write("                                    <div class=\"form-check form-check-inline \">\r\n");
      out.write("                                        <input class=\"form-check-input v-check-input shadow-none\" type=\"radio\"\r\n");
      out.write("                                            name=\"gridRadios\" id=\"gtnam\" value=\"option1\" checked>\r\n");
      out.write("                                        <label class=\"form-check-label\" for=\"gridRadios1\">\r\n");
      out.write("                                            Nam\r\n");
      out.write("                                        </label>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"form-check form-check-inline \">\r\n");
      out.write("                                        <input class=\"form-check-input v-check-input shadow-none\" type=\"radio\"\r\n");
      out.write("                                            name=\"gridRadios\" id=\"gtnu\" value=\"option2\">\r\n");
      out.write("                                        <label class=\"form-check-label\" for=\"gridRadios2\">\r\n");
      out.write("                                            Nữ\r\n");
      out.write("                                        </label>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"row mb-3\">\r\n");
      out.write("                                <label for=\"Twitter\" class=\"col-md-4 col-lg-3 col-form-label v-label\">Trạng thái</label>\r\n");
      out.write("                                <div class=\"col-md-8 col-lg-9\">\r\n");
      out.write("                                    <select class=\"form-select v-form-control\" aria-label=\" select example\">\r\n");
      out.write("                                        <option selected value=\"1\">One</option>\r\n");
      out.write("                                        <option value=\"2\">Two</option>\r\n");
      out.write("                                    </select>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"text-center\">\r\n");
      out.write("                                <button type=\"submit\" class=\"btn btn-primary btn-main-color border-0 shadow-none\"\r\n");
      out.write("                                    style=\"padding: 8px 20px\">Lưu\r\n");
      out.write("                                </button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </form><!-- End Profile Edit Form -->\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- end profile -->\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- End ProfileEditModal-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Vertically centered Modal -->\r\n");
      out.write("    <div class=\"modal fade\" id=\"verticalycentered\" tabindex=\"-1\">\r\n");
      out.write("        <div class=\"modal-dialog modal-dialog-centered v-modal-add\">\r\n");
      out.write("            <div class=\"modal-content border-0\">\r\n");
      out.write("                <div class=\"modal-header v-modal-header\">\r\n");
      out.write("                    <h5 class=\"modal-title v-modal-title\">Thêm</h5>\r\n");
      out.write("                    <button type=\"button\" class=\"btn shadow-none\" data-bs-dismiss=\"modal\" aria-label=\"Close\"\r\n");
      out.write("                        style=\"font-weight:700\"><i class=\"bi bi-x v-icon-close\"></i></button>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"modal-body modal-add\">\r\n");
      out.write("                    <!-- Profile Edit Form -->\r\n");
      out.write("                    <form>\r\n");
      out.write("                        <div class=\"row mb-3\">\r\n");
      out.write("                            <label for=\"fullName\" class=\"col-md-4 col-lg-3 col-form-label v-label\">Mã nhân viên</label>\r\n");
      out.write("                            <div class=\"col-md-8 col-lg-9\">\r\n");
      out.write("                                <input name=\"fullName\" type=\"text\" class=\"form-control v-form-control\" id=\"fullName\"\r\n");
      out.write("                                    value=\"Kevin Anderson\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"row mb-3\">\r\n");
      out.write("                            <label for=\"company\" class=\"col-md-3 col-form-label v-label\">Họ</label>\r\n");
      out.write("                            <div class=\"col-md-3\">\r\n");
      out.write("                                <input name=\"company\" type=\"text\" class=\"form-control v-form-control\" id=\"company\"\r\n");
      out.write("                                    value=\"Lueilwitz, Wisoky and Leuschke\">\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <label for=\"Job\" class=\"col-md-1 col-form-label v-label\">Tên</label>\r\n");
      out.write("                            <div class=\"col-md-5\">\r\n");
      out.write("                                <input name=\"job\" type=\"text\" class=\"form-control  v-form-control\" id=\"Job\"\r\n");
      out.write("                                    value=\"Web Designer\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"row mb-3\">\r\n");
      out.write("                            <label for=\"Twitter\" class=\"col-md-4 col-lg-3 col-form-label v-label\">Username</label>\r\n");
      out.write("                            <div class=\"col-md-8 col-lg-9\">\r\n");
      out.write("                                <input name=\"twitter\" type=\"text\" class=\"form-control v-form-control\" id=\"Twitter\"\r\n");
      out.write("                                    value=\"https://twitter.com/#\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"row mb-3\">\r\n");
      out.write("                            <label for=\"Twitter\" class=\"col-md-4 col-lg-3 col-form-label v-label\">Email</label>\r\n");
      out.write("                            <div class=\"col-md-8 col-lg-9\">\r\n");
      out.write("                                <input type=\"email\" class=\"form-control v-form-control\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"row mb-3\">\r\n");
      out.write("                            <label for=\"Twitter\" class=\"col-md-4 col-lg-3 col-form-label v-label\">Mật Khẩu</label>\r\n");
      out.write("                            <div class=\"col-md-8 col-lg-9\">\r\n");
      out.write("                                <input type=\"password\" class=\"form-control v-form-control\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"row mb-3\">\r\n");
      out.write("                            <label for=\"Twitter\" class=\"col-md-4 col-lg-3 col-form-label v-label\">Nhập lại mật\r\n");
      out.write("                                Khẩu</label>\r\n");
      out.write("                            <div class=\"col-md-8 col-lg-9\">\r\n");
      out.write("                                <input type=\"password\" class=\"form-control v-form-control\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"row mb-3\">\r\n");
      out.write("                            <label for=\"Twitter\" class=\"col-md-4 col-lg-3 col-form-label v-label\">Vai trò</label>\r\n");
      out.write("                            <div class=\"col-md-8 col-lg-9\">\r\n");
      out.write("                                <select class=\"form-select v-form-control\" aria-label=\" select example\">\r\n");
      out.write("                                    <option selected value=\"1\">One</option>\r\n");
      out.write("                                    <option value=\"2\">Two</option>\r\n");
      out.write("                                    <option value=\"3\">Three</option>\r\n");
      out.write("                                </select>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"row mb-3\">\r\n");
      out.write("                            <label for=\"Country\" class=\"col-md-4 col-lg-3 col-form-label v-label\">CMND/CCCD</label>\r\n");
      out.write("                            <div class=\"col-md-8 col-lg-9\">\r\n");
      out.write("                                <input name=\"country\" type=\"text\" class=\"form-control v-form-control\" id=\"Country\"\r\n");
      out.write("                                    value=\"USA\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"row mb-3\">\r\n");
      out.write("                            <label for=\"Address\" class=\"col-md-4 col-lg-3 col-form-label v-label\">SĐT</label>\r\n");
      out.write("                            <div class=\"col-md-8 col-lg-9\">\r\n");
      out.write("                                <input name=\"address\" type=\"text\" class=\"form-control v-form-control\" id=\"Address\"\r\n");
      out.write("                                    value=\"A108 Adam Street, New York, NY 535022\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"row mb-3\">\r\n");
      out.write("                            <label for=\"Phone\" class=\"col-md-4 col-lg-3 col-form-label v-label\">Ngày sinh</label>\r\n");
      out.write("                            <div class=\"col-md-8 col-lg-9\">\r\n");
      out.write("                                <input name=\"phone\" type=\"text\" class=\"form-control v-form-control\" id=\"Phone\"\r\n");
      out.write("                                    value=\"(436) 486-3538 x29071\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"row mb-3\">\r\n");
      out.write("                            <label for=\"Email\" class=\"col-md-4 col-lg-3 col-form-label v-label\">Phái</label>\r\n");
      out.write("                            <div class=\"col-md-8\">\r\n");
      out.write("                                <div class=\"form-check form-check-inline \">\r\n");
      out.write("                                    <input class=\"form-check-input v-check-input shadow-none\" type=\"radio\"\r\n");
      out.write("                                        name=\"gridRadios\" id=\"gtnam\" value=\"option1\" checked>\r\n");
      out.write("                                    <label class=\"form-check-label\" for=\"gridRadios1\">\r\n");
      out.write("                                        Nam\r\n");
      out.write("                                    </label>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"form-check form-check-inline \">\r\n");
      out.write("                                    <input class=\"form-check-input v-check-input shadow-none\" type=\"radio\"\r\n");
      out.write("                                        name=\"gridRadios\" id=\"gtnu\" value=\"option2\">\r\n");
      out.write("                                    <label class=\"form-check-label\" for=\"gridRadios2\">\r\n");
      out.write("                                        Nữ\r\n");
      out.write("                                    </label>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"text-center\">\r\n");
      out.write("                            <button type=\"submit\" class=\"btn btn-primary btn-main-color border-0 shadow-none\"\r\n");
      out.write("                                style=\"padding: 8px 20px\">Lưu\r\n");
      out.write("                            </button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </form><!-- End Profile Edit Form -->\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div><!-- End Vertically centered Modal-->\r\n");
      out.write("    <!-- Vendor JS Files -->\r\n");
      out.write("    <script src=\"../assets/vendor/apexcharts/apexcharts.min.js\"></script>\r\n");
      out.write("    <script src=\"../assets/vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    <script src=\"../assets/vendor/chart.js/chart.min.js\"></script>\r\n");
      out.write("    <script src=\"../assets/vendor/echarts/echarts.min.js\"></script>\r\n");
      out.write("    <script src=\"../assets/vendor/quill/quill.min.js\"></script>\r\n");
      out.write("    <script src=\"../assets/vendor/simple-datatables/simple-datatables.js\"></script>\r\n");
      out.write("    <script src=\"../assets/vendor/tinymce/tinymce.min.js\"></script>\r\n");
      out.write("    <script src=\"../assets/vendor/php-email-form/validate.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Template Main JS File -->\r\n");
      out.write("    <script src=\"../assets/js/main.js\"></script>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /WEB-INF/views/QuanLy/head.jsp(10,14) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/resources/assets/img/favicon.png");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f1_reused = false;
    try {
      _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f1.setParent(null);
      // /WEB-INF/views/QuanLy/head.jsp(11,14) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f1.setValue("/resources/assets/img/apple-touch-icon.png");
      int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
      if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      _jspx_th_c_005furl_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f1, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f2 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f2_reused = false;
    try {
      _jspx_th_c_005furl_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f2.setParent(null);
      // /WEB-INF/views/QuanLy/head.jsp(21,14) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f2.setValue("/resources/assets/vendor/bootstrap/css/bootstrap.min.css");
      int _jspx_eval_c_005furl_005f2 = _jspx_th_c_005furl_005f2.doStartTag();
      if (_jspx_th_c_005furl_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
      _jspx_th_c_005furl_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f2, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f3 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f3_reused = false;
    try {
      _jspx_th_c_005furl_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f3.setParent(null);
      // /WEB-INF/views/QuanLy/head.jsp(22,14) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f3.setValue("/resources/assets/vendor/bootstrap-icons/bootstrap-icons.css");
      int _jspx_eval_c_005furl_005f3 = _jspx_th_c_005furl_005f3.doStartTag();
      if (_jspx_th_c_005furl_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f3);
      _jspx_th_c_005furl_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f3, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f4 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f4_reused = false;
    try {
      _jspx_th_c_005furl_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f4.setParent(null);
      // /WEB-INF/views/QuanLy/head.jsp(23,14) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f4.setValue("/resources/assets/vendor/boxicons/css/boxicons.min.css");
      int _jspx_eval_c_005furl_005f4 = _jspx_th_c_005furl_005f4.doStartTag();
      if (_jspx_th_c_005furl_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f4);
      _jspx_th_c_005furl_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f4, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f5 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f5_reused = false;
    try {
      _jspx_th_c_005furl_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f5.setParent(null);
      // /WEB-INF/views/QuanLy/head.jsp(24,14) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f5.setValue("/resources/assets/vendor/quill/quill.snow.css");
      int _jspx_eval_c_005furl_005f5 = _jspx_th_c_005furl_005f5.doStartTag();
      if (_jspx_th_c_005furl_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f5);
      _jspx_th_c_005furl_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f5, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f6 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f6_reused = false;
    try {
      _jspx_th_c_005furl_005f6.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f6.setParent(null);
      // /WEB-INF/views/QuanLy/head.jsp(25,14) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f6.setValue("/resources/assets/vendor/quill/quill.bubble.css");
      int _jspx_eval_c_005furl_005f6 = _jspx_th_c_005furl_005f6.doStartTag();
      if (_jspx_th_c_005furl_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f6);
      _jspx_th_c_005furl_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f6, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f7 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f7_reused = false;
    try {
      _jspx_th_c_005furl_005f7.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f7.setParent(null);
      // /WEB-INF/views/QuanLy/head.jsp(26,14) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f7.setValue("/resources/assets/vendor/remixicon/remixicon.css");
      int _jspx_eval_c_005furl_005f7 = _jspx_th_c_005furl_005f7.doStartTag();
      if (_jspx_th_c_005furl_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f7);
      _jspx_th_c_005furl_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f7, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f7_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f8(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f8 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f8_reused = false;
    try {
      _jspx_th_c_005furl_005f8.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f8.setParent(null);
      // /WEB-INF/views/QuanLy/head.jsp(27,14) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f8.setValue("/resources/assets/vendor/simple-datatables/style.css");
      int _jspx_eval_c_005furl_005f8 = _jspx_th_c_005furl_005f8.doStartTag();
      if (_jspx_th_c_005furl_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f8);
      _jspx_th_c_005furl_005f8_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f8, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f8_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f9(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f9 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f9_reused = false;
    try {
      _jspx_th_c_005furl_005f9.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f9.setParent(null);
      // /WEB-INF/views/QuanLy/head.jsp(30,14) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f9.setValue("/resources/assets/css/style.css");
      int _jspx_eval_c_005furl_005f9 = _jspx_th_c_005furl_005f9.doStartTag();
      if (_jspx_th_c_005furl_005f9.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f9);
      _jspx_th_c_005furl_005f9_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f9, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f9_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f10(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f10 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f10_reused = false;
    try {
      _jspx_th_c_005furl_005f10.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f10.setParent(null);
      // /WEB-INF/views/QuanLy/head.jsp(31,14) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f10.setValue("/resources/assets/css/style-v.css");
      int _jspx_eval_c_005furl_005f10 = _jspx_th_c_005furl_005f10.doStartTag();
      if (_jspx_th_c_005furl_005f10.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f10);
      _jspx_th_c_005furl_005f10_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f10, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f10_reused);
    }
    return false;
  }
}
